### ISSUE TITLE
Term Length show wrong result in practice

### ISSUE THREAD

**Issue by qqonline** [hicommonwealth/edgeware-lockdrop-ui#11]
I tried to practice with Ropsten testnet.

I tried to lock with 3 months in one transaction and another locked with 6 months.

however, when I query the state in this page: https://stats.edgewa.re/

it shows all these two transaction's Term Length are 12 months.

may be this is a bug?

![微信截图_20190610164742](https://user-images.githubusercontent.com/1336978/59183875-7f1a4600-8b9f-11e9-9354-7ae089e74fe3.png)

**Comment by drewstone** [comment]
Yes it is a UI bug. Should be fixed soon!
