### ISSUE TITLE
Lockdrop instructions suggest too low Gas Limit for MyCrypto

### ISSUE THREAD

**Issue by fkbenjamin** [hicommonwealth/edgeware-lockdrop-ui#6]
On [the lockdrop website](https://edgewa.re/lockdrop/), if you select MyCrypto to submit your transaction, at `Step 6.` it suggests to

```
Uncheck 'Automatically Calculate Gas Limit' and set your gas limit to 100000.
Sign and send the transaction.
```

However, 100k Gas Limit is too low and the transactions will run out of gas. See some examples with 100k and 120k Gas limit here:

[100k Gas Limit](
https://ropsten.etherscan.io/tx/0xc814cd8e28327410ec273a0cfd5383c6a119c002b3c0646b930cbd138a76d1cd)
[120k Gas Limit](https://ropsten.etherscan.io/tx/0xc47eabe20b9ce9013dcd19fc28618d85375e4d45c286ca19ed33778b41bc2f4c)

From some succesfull transactions, I can tell that the consumed gas is somewhere around ~123k Gas. I would suggest do change the Gas Limit suggested in the description to the same used by MetaMask, which is 150k.

Best,

Florian from Staking Facilities

**Comment by drewstone** [comment]
Thanks, I will change to this as well.
