### ISSUE TITLE
Lockdrop page requires web3 provider to work

### ISSUE THREAD

**Issue by fkbenjamin** [hicommonwealth/edgeware-lockdrop-ui#7]
When accessing the lockdrop page from a browser with no web3 provider (like MetaMask) enabled, the page will not work. In the developer console, you can see the following error, indicating that it did not find a web3 provider injected in the browser:

````
Cannot read property 'isToshi' of undefined
````

There is no error message visible on the page and the submit transaction buttons are not clickable anymore if no provider is available (MyCrypto for example would not require to have a web3 provider injected).

This will be an issue, since I assume there are plenty of people who use their ledger and MyCrypto and have no web3 provider installed.

**Comment by drewstone** [comment]
Should be fixed soon, thanks for letting us know!
